Identity:
  GenerateNewKey: true
Server:
  Port: 9010
  Host: 192.168.1.220
  DhtServerMode: 'true'
Redis:
  Host: 127.0.0.1
  Port: 6379
  Tl2NlChannel: iris_internal
PeerDiscovery:
  DisableBootstrappingNodes: false
  ListOfMultiAddresses:
  - /dns/kilimanjaro.felk.cvut.cz/udp/6437/quic 12D3KooWJJa9PpMFVP7s3TQs2sedypJXxtMVkphRhgkjGH9EYMfM
