Identity:
  GenerateNewKey: true
Server:
  Port: 9010
  Host: null
  DhtServerMode: 'true'
Redis:
  Host: 127.0.0.1
  Port: 6644
  Tl2NlChannel: iris_internal
PeerDiscovery:
  DisableBootstrappingNodes: true
