name: CI-production-testing

on:
  pull_request:
    branches:
    - 'master'
    - '!develop'

jobs:

  unit_and_integration_tests:
    # runs the tests on a GH VM
    runs-on: ubuntu-22.04
    # 2 hours timeout
    timeout-minutes: 7200


    steps:
    - uses: actions/checkout@v4
      with:
        ref: 'develop'
        # Fetch all history for all tags and branches
        fetch-depth: ''

    - name: Install slips dependencies
      run: sudo apt-get update --fix-missing && sudo apt-get -y --no-install-recommends install python3 redis-server python3-pip python3-certifi python3-dev build-essential file lsof net-tools iproute2 iptables python3-tzlocal nfdump tshark git whois golang nodejs notify-osd yara libnotify-bin

    - name: Install Zeek
      run: |
        sudo echo 'deb http://download.opensuse.org/repositories/security:/zeek/xUbuntu_22.04/ /' | sudo tee /etc/apt/sources.list.d/security:zeek.list
        curl -fsSL https://download.opensuse.org/repositories/security:zeek/xUbuntu_22.04/Release.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/security_zeek.gpg > /dev/null
        sudo apt update && sudo apt install -y --no-install-recommends --fix-missing zeek
        sudo ln -s /opt/zeek/bin/zeek /usr/local/bin/bro

    - name: Set up Python 3.10.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.10.12"

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        python3 -m pip install --no-cache-dir -r install/requirements.txt

    - name: Start redis server
      run: redis-server --daemonize yes


    - name: Run database unit tests
      run: |
        python3 -m pytest tests/test_database.py -p no:warnings -vv

    - name: main unit tests
      run: |
        python3 -m pytest tests/test_main.py -p no:warnings -vv

    - name: Flowalerts Unit Tests
      run: |
        python3 -m pytest tests/test_flowalerts.py -p no:warnings -vv

    - name: conn Unit Tests
      run: |
        python3 -m pytest tests/test_conn.py -p no:warnings -vv

    - name: downloaded file Unit Tests
      run: |
        python3 -m pytest tests/test_downloaded_file.py -p no:warnings -vv

    - name: SSL Unit Tests
      run: |
        python3 -m pytest tests/test_ssl.py -p no:warnings -vv

    - name: Tunnel Unit Tests
      run: |
        python3 -m pytest tests/test_tunnel.py -p no:warnings -vv

    - name: SSH Unit Tests
      run: |
        python3 -m pytest tests/test_ssh.py -p no:warnings -vv


    - name: dns Unit Tests
      run: |
        python3 -m pytest tests/test_dns.py -p no:warnings -vv

    - name: Notice Unit Tests
      run: |
        python3 -m pytest tests/test_notice.py -p no:warnings -vv

    - name: Software Unit Tests
      run: |
        python3 -m pytest tests/test_software.py -p no:warnings -vv

    - name: SMTP Unit Tests
      run: |
        python3 -m pytest tests/test_smtp.py -p no:warnings -vv

    - name: Whitelist Unit Tests
      run: |
        python3 -m pytest tests/test_whitelist.py -p no:warnings -vv

    - name: ARP Unit Tests
      run: |
        python3 -m pytest tests/test_arp.py -p no:warnings -vv

    - name: Blocking Unit Tests
      run: |
        python3 -m pytest tests/test_blocking.py -p no:warnings -vv

    - name: Flow handler Unit Tests
      run: |
        python3 -m pytest tests/test_flow_handler.py -p no:warnings -vv

    - name: Horizontal Portscans Unit Tests
      run: |
        python3 -m pytest tests/test_horizontal_portscans.py -p no:warnings -vv

    - name: HTTP Analyzer Unit Tests
      run: |
        python3 -m pytest tests/test_http_analyzer.py -p no:warnings -vv

    - name: Vertical Portscans Unit Tests
      run: |
        python3 -m pytest tests/test_vertical_portscans.py -p no:warnings -vv

    - name: Network Discovery Unit Tests
      run: |
        python3 -m pytest tests/test_network_discovery.py -p no:warnings -vv

    - name: Virustotal Unit Tests
      run: |
        python3 -m pytest tests/test_virustotal.py -p no:warnings -vv

    - name: Update Manager Unit tests
      run: |
        python3 -m pytest tests/test_update_file_manager.py -p no:warnings -vv

    - name: Threat Intelligence Unit tests
      run: |
        python3 -m pytest tests/test_threat_intelligence.py -p no:warnings -vv

    - name: Slips Utils Unit tests
      run: |
        python3 -m pytest tests/test_slips_utils.py -p no:warnings -vv

    - name: Slips.py Unit Tests
      run: |
        python3 -m pytest tests/test_slips.py -p no:warnings -vv

    - name: Profiler Unit Tests
      run: |
        python3 -m pytest tests/test_profiler.py -p no:warnings -vv

    - name: Leak Detector Unit Tests
      run: |
        python3 -m pytest tests/test_leak_detector.py -p no:warnings -vv

    - name: Ipinfo Unit Tests
      run: |
        python3 -m pytest tests/test_ip_info.py -p no:warnings -vv

    - name: Evidence tests
      run: |
        python3 -m pytest -s tests/test_evidence.py -p no:warnings -vv

    - name: ASN info Unit Tests
      run: |
        python3 -m pytest tests/test_asn_info.py -p no:warnings -vv

    - name: Urlhaus Unit Tests
      run: |
        python3 -m pytest tests/test_urlhaus.py -p no:warnings -vv

    - name: Input Unit Tests
      run: |
        python3 -m pytest tests/test_inputProc.py -p no:warnings -vv
        
    - name: progress_bar Unit Tests
      run: |
        python3 -m pytest tests/test_progress_bar.py -p no:warnings -vv    

    - name: daemon Tests
      run: |
        python3 -m pytest tests/test_daemon.py -p no:warnings -vv    

    - name: Clear redis cache
      run: ./slips.py -cc

    - name: go_director Unit Tests
      run: |
        python3 -m pytest tests/test_go_director.py -p no:warnings -vv
    
    - name: Clear redis cache
      run: ./slips.py -cc

    - name: notify Tests
      run: |
        python3 -m pytest tests/test_notify.py -p no:warnings -vv
    
    - name: set Evidence Unit Tests
      run: |
        python3 -m pytest tests/test_set_evidence.py -p no:warnings -vv

    - name: Output Unit Tests
      run: |
        python3 -m pytest tests/test_output.py -p no:warnings -vv

    - name: idea format Unit Tests
      run: |
        python3 -m pytest tests/test_idea_format.py -p no:warnings -vv    


    - name: Clear redis cache
      run: ./slips.py -cc



    - name: Config file tests
      run: |
        python3 -m pytest -s tests/integration_tests/test_config_files.py  -p no:warnings -vv

    - name: Portscan tests
      run: |
        python3 -m pytest -s tests/integration_tests/test_portscans.py -p no:warnings -vv

    - name: Dataset Integration tests
      run: |
        python3 -m pytest -s tests/integration_tests/test_dataset.py -p no:warnings -vv


    - name: Upload Artifacts
      # run this job whether the above jobs failed or passed
      if: success() || failure()
      uses: actions/upload-artifact@v3
      with:
        name: test_slips_locally-integration-tests-output
        path: |
          output/integration_tests
